name: Push to Replicate

on:
  push:
    branches: [ main ]
    paths:
      - "cog.yaml"
      - "predict.py"
      - "requirements.txt"
      - ".github/workflows/push.yml"
  workflow_dispatch:
    inputs:
      image:
        description: "Optional: r8.im/<owner>/<model> (overrides cog.yaml image)"
        required: false
        default: ""

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # Optional: free some space so builds don't run out of disk
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          # Create this secret in your repo settings (see steps below)
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push model to Replicate
        run: |
          set -euxo pipefail
          IMAGE_INPUT="${{ github.event.inputs.image }}"
          if [ -n "$IMAGE_INPUT" ]; then
            cog push "$IMAGE_INPUT"
          else
            # uses the `image:` field from cog.yaml
            cog push
          fi
